# Generated by Django 4.2.1 on 2023-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas_banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=250)),
                ('nivel_1', models.CharField(max_length=250)),
                ('nivel_2', models.CharField(max_length=250)),
                ('nivel_3', models.CharField(max_length=250)),
                ('nivel_4', models.CharField(max_length=250)),
                ('anio_mes', models.CharField(max_length=250)),
                ('valor', models.CharField(max_length=250)),
            ],
        ),
    ]
